M48
; DRILL file {KiCad (6.0.6)} date Tue Aug 16 14:43:34 2022
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-08-16T14:43:34+09:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.6)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1378
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.3543
%
G90
G05
T1
X4.4947Y-3.0183
X4.4947Y-4.8557
X6.3321Y-3.0183
X6.3321Y-4.8557
T2
X6.47Y-4.44
T0
M30
